--- STEAMODDED HEADER
--- MOD_NAME: stickers
--- MOD_ID: stickers
--- PREFIX: stickers
--- MOD_AUTHOR: [OceanRamen]
--- MOD_DESCRIPTION: Displays your stake stickers on your jokers!
--- VERSION: 0.0.1a
--- LOADER_VERSION_GEQ: 1.0.0
